---
version: '3'
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    volumes:
      - type: bind
        source: /Volumes/Kratos/Docker/Overseerr/overseerr-data
        target: /app/config
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    environment:
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.domain.com`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
    restart: unless-stopped
