---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /Volumes/Kratos/Docker/Komga/config
        target: /config
      - type: bind
        source: /Volumes/Kratos/Comics
        target: /comics
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 8080:8080
    user: "1000:1000"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx6g
    restart: unless-stopped
