version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      PIHOLE_BASE: /Volumes/Kratos/Docker/PiHole/pihole-storage
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
    - type: bind
      source: /Volumes/Kratos/Docker/PiHole/etc-pihole
      target: /etc/pihole
    - type: bind
      source: /Volumes/Kratos/Docker/PiHole/etc-dnsmasq.d
      target: /etc/dnsmasq.d
    - type: bind
      source: /etc/timezone
      target: /etc/timezone
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
